### ISSUE TITLE
Print Time in filename

### ISSUE THREAD

**Issue by RicXXX** [rgomezjnr/GcodeFilenameFormat#1]
Hello,
Do you have a way to add the print time to the filename?
I  read the documentation, but nothing.

I know it is possible, the "custom printjob prefix" plugin can do it, but I believe is more logic to have it after the filename.

Thanks for any feedback

**Comment by rgomezjnr** [comment]
Hello Ric,

I just tested Custom Printjob Prefix plugin together with Gocde Filename Format plugin.

The following printjob prefix:

`{printer_name} print_time {print_time_hours}h{print_time_minutes}m
`

results in this gcode with the default gcode filename format:

`PI3MK3MK3S print-time 0h3m_paperclip Prusa Research PLA lw 0.4mm lh 0.15mm if 20% ext1 215.0C bed 65.0C.gcode`

Does that work for you? Or do you want to have the print time at the end of the filename?

> but I believe is more logic to have it after the filename.

I think to add the print time to the end I would have to add this option in Gcode Filename Format. I've looked at the source code for Printjob Prefix and I think it would be very easy to add this to the Filename Format plugin (https://github.com/fieldOfView/Cura-CustomJobPrefix/blob/master/PrintInformationPatches.py#L83).

@fieldOfView - Any thoughts on this? There is some overlap between our two plugins.

**Comment by RicXXX** [comment]
Hi,
thanks for the quick reply.
Yes I've tried the "prefix" plugin, but I prefer very much your plugin that put the selected option after the filename.

If you can add the "print time" option to your plugin (as you wrote should be very easy) it will be appreciated and a good upgrade to your nice plugin.

By the way: can you also add the "length of the filament used" as option of your plugin?

Thanks for your work
Ciao

**Comment by rgomezjnr** [comment]
I'll see if I can these additional settings Ric.

I know there are a number of additional settings that users may also want to use so I'm happy to improve the plugin.

**Comment by fieldOfView** [comment]
> Any thoughts on this? There is some overlap between our two plugins.

I agree that there is quite a bit of overlap in functionality, though it is interesting to see how different our implementations are. I think both approaches have their pros and cons, but in the long run I don't know if keeping both solutions is the best use of our time and energy.

**Comment by rgomezjnr** [comment]
The nice thing is that both plugins are compatible. Gcode Filename Format will use the naming from  Custom Printjob Prefix in the [base_name] setting. Just in @RicXXX's case he wants to append the print time at the end of the filename, not as part of the print job name.

I'm open to further discussion and collaboration. I agree there may be a better solution.

In the meantime I will attempt to add these additional settings in Gcode Filename Format.

**Comment by rgomezjnr** [comment]
Hello @RicXXX,

I added the print time and length in [1.2.1-rc1](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/1.2.1-rc1). Can you please review the plugin? You will need to download it and place it in your Cura plugins folder.

The following format:
`[base_name] print info [print_time_hours_all]h[print_time_minutes]min [material_length]m $[material_cost]`

results in this filename:
`PI3MK3M_paperclip print info 0h2min 0.1m $0.01.gcode`

Here is the updated [README](https://github.com/rgomezjnr/GcodeFilenameFormat/blob/print-information/README.md).

If it works for you I can publish the update to the Cura Marketplace.

**Comment by RicXXX** [comment]
Hello,
and thanks for your job.
It works.

If I may: in the weight details I believe you can delete the decimals (to
have 7g instead of 7.0g). Decimals of grams is useless.

I was looking to make a review, but I did not find anyplace on cura market
or on github (On github I put a star, but that's all I find.
So where to review as you asked?

Thanks
Ciao
Ric

Il giorno sab 21 mar 2020 alle ore 06:30 rgomezjnr <notifications@github.com>
ha scritto:

**Comment by rgomezjnr** [comment]
Thanks for the feedback Ric. I will remove the decimal from the weight. You don't have to leave a review. I was just looking for your feedback which you have given me.

**Comment by rgomezjnr** [comment]
I removed the decimals from the weight in [1.2.1-rc2](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/1.2.1-rc2).

I will submit version 1.2.1 to the Cura Marketplace.

**Comment by RicXXX** [comment]
Thanks again
Great Job
