### ISSUE TITLE
Feature Request - Tie format to printer

### ISSUE THREAD

**Issue by KenLucke** [rgomezjnr/GcodeFilenameFormat#12]
I'm baaa-aaaackkkk..... :)

Can you add an option to tie the format to specific printer profile?  I'd like to add something automatically into the format [not at the beginning, as the "prefix machine name" or whatever that option is] to identify for which printer it was sliced.

So I could do this (for example, with two of my printers, "Yellow" and "Blue", just by changing profiles, so I would not have to squint at the names to see that one is set up for one of my direct drive printers, the other for one of my Bowden tube printers):
```
Druid - Threaded PLA [Yellow] skirt|Infill 15%,cubic|Noz 0.4|LH 0.1|LW 0.4|Temps 230.0°,60°|Speed 50|RT 1,45|Support tree,63°|Coast-True

Druid - Threaded PLA [Blue] skirt|Infill 15%,cubic|Noz 0.4|LH 0.1|LW 0.4|Temps 230.0°,60°|Speed 50|RT 5,55|Support tree,63°|Coast-True
```

I can manually add the name into the file as I am saving it, but I sometimes forget.

**Comment by KenLucke** [comment]
Nevermind, I found the `machine_name` parameter.

**Comment by KenLucke** [comment]
well, `machine_name` only uses the model name, so it won't work for me, and I can't find anything that identifies a specific machine profile in the .json list, so I'm back to the original request.

I think that the easiest way to doi this might be to add an item for "printer_profile_name" that pulls it from Cura's active profile.

**Comment by rgomezjnr** [comment]
Haha hello again Ken! I hope you have been having fun printing.

I think what you're asking for has been added in the [update-job-name](https://github.com/rgomezjnr/GcodeFilenameFormat/tree/update-job-name) branch with the **profile-name** option. For example, 

[abbr_machine] [profile_name] [base_name] [brand] [material] lw [line_width]mm lh [layer_height]mm if [infill_sparse_density]% ext1 [material_print_temperature]C bed [material_bed_temperature]C

PI3MK3M MK3S_MK3_0.2_Fast paperclip Generic PLA lw 0.8mm lh 0.4mm if 15% ext1 215C bed 65C.gcode

Does that work for you?

**Comment by KenLucke** [comment]
I think that is the print profile, not the printer profile, but I will check.

**Comment by KenLucke** [comment]
Yeah, I was correct, that's the name of the printer settings profile, not the name of the printer itself from th printer profile.

<img width="908" alt="image" src="https://user-images.githubusercontent.com/57936294/115274351-67923980-a0f5-11eb-9b54-7a2c5012fce5.png">

**Comment by rgomezjnr** [comment]
I misinterpreted your question. You tried [machine_name]. Have you tried [printer_name]?

Did you happen to use the Rename button in the printer preferences?

**Comment by KenLucke** [comment]
Yes, I renamed the printer.

Using [printer_name] works properly for my purposes.  Thanks, I could not find that.
