### ISSUE TITLE
Using material display name

### ISSUE THREAD

**Issue by Pukwudji** [rgomezjnr/GcodeFilenameFormat#14]
Hi, I use the material display name field to differentiate between PLA and PLA+, (using material type invalidates profiles), would it be possible to add this option to the settings?
I did check:https://github.com/Ultimaker/Cura/blob/master/resources/i18n/fdmprinter.def.json.pot but couldn't see a relevant setting.
Cheers

**Comment by rgomezjnr** [comment]
Hi Pukwdji I just tested this behavior with the following and had no issues. I see that changes to the material profile name are not reflected in the [material] format option, but changing the material type name did work as expected. I created a custom PLA+ profile with the material type set to PLA+ and the gcode filename was correct.

- Cura 4.9.0
- GcodeFilenameFormat 1.4.1
- Default GcodeFilenameFormat string

What do you mean "(using material type invalidates profiles)"?
What version of Cura and GcodeFilenameFormat are you using?

![image](https://user-images.githubusercontent.com/55524335/118211624-3faaa300-b421-11eb-9d8d-20978e679670.png)
![image](https://user-images.githubusercontent.com/55524335/118213055-0cb4df00-b422-11eb-9ef7-cbbe1fd56501.png)

**Comment by rgomezjnr** [comment]
Hello @Pukwudji have you had a chance to see my response? I wasn't able to replicate your issue. Did I understand your question correctly?
