### ISSUE TITLE
None of date/time placeholder is working on Linux

### ISSUE THREAD

**Issue by jeferod83** [rgomezjnr/GcodeFilenameFormat#15]
Hi! 

On Ultimaker Cura 4.8, Linux 64 Bits (Kubuntu 21.04) version, all the place holders for date and time aren't working.

Steps to reproduce:

1) On extension menu, choose "Gcode Filename Format" -> "Edit Format".
2) Put any date/time placeholder on the text input, beside brackets, for example "[date][time]" or "[year][month][day]"
3) Slice and select to "save gcode".
4) The replaced text is "none" on each placeholder related to date/time.

Thanks for the attention!

**Comment by rgomezjnr** [comment]
Hi jeferod83.

Can you confirm you're using the GFF version 1.4.1 from the Cura Marketplace?

The datetime format options haven't been added to a new release. The datetime format options are only in release candidate version 2.0.0-rc3 at the moment.

I submitted a new version of this plugin, [Gcode Filename Format Plus](https://github.com/rgomezjnr/GcodeFilenameFormatPlus), a few days ago. This includes the datetime options as well as other improvements. It should be accepted and available for download in the Cura Marketplace soon.
I will likely be marking Gcode Filename Format as deprecated and redirecting visitors to GFF+.

In the mean time if you're comfortable doing so you can download GFF [2.0.0-rc3](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/2.0.0-rc3) and manually install it. 

Does this answer your question? Would you like additional help installing 2.0.0-rc3?

**Comment by jeferod83** [comment]
Hi @rgomezjnr! Thanks for the reply!

Yeah, I've installed GFF from Cura Marketplace. I can't see the version exactly, because I'm working on Windows for now. When I start on my Linux S.O. I'll try to see if the version matches with the version that you've mentioned, but, how the Cura installation is recently (from past week), I believe the version of GFF is recent too.

So, thanks a lot for the quickly reply and I'll think what I'll do.

Best regards,
Jeferson

**Comment by rgomezjnr** [comment]
Hey Jeferson [GFF+](https://marketplace.ultimaker.com/app/cura/plugins/rgomezjnr/GcodeFilenameFormatPlus) is now available in the Cura Marketplace. I recommend trying it instead of GFF since it does contain the datetime format options. Let me know if you have any questions or feedback, thanks.

**Comment by rgomezjnr** [comment]
Hey Jeferson do you still have this issue in GFF+?
