### ISSUE TITLE
Add machine prefix to job name setting not working

### ISSUE THREAD

**Issue by liam-maps** [rgomezjnr/GcodeFilenameFormat#16]
Hello.
I've disabled "Add machine prefix to job name" in Cura settings but the filename generated by your program still adds the printer name.
I'm using Cura 4.11.
Thank you.

**Comment by rgomezjnr** [comment]
Hello liam can you see if the same behavior exists in [GcodeFilenameFormatPlus](https://marketplace.ultimaker.com/app/cura/plugins/rgomezjnr/GcodeFilenameFormatPlus)? That is the newer version of the plugin that I'm actively supporting.

**Comment by rgomezjnr** [comment]
liam were you able to try GcodeFilenameFormatPlus?

**Comment by liam-maps** [comment]
> liam were you able to try GcodeFilenameFormatPlus?

I'm so sorry for being missing for so long.
That indeed helped me.
Thank you very much for your work.
