### ISSUE TITLE
Name of profile

### ISSUE THREAD

**Issue by Di3mex** [rgomezjnr/GcodeFilenameFormat#3]
I seem to not be able to find the string for the name of the profile that was used to create the gcode.

**Comment by rgomezjnr** [comment]
Hi Di3mex the plugin doesn't support the profile name in the format. I'll look into adding this.

**Comment by rgomezjnr** [comment]
I added the [profile_name] option in [1.3.1-rc1](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/1.3.1-rc1).

Can you please verify this is working for you? You will need to download the plugin and copy it to your Cura plugins folder.

Thank you

**Comment by Di3mex** [comment]
Thanks :-)
Works for me.

**Comment by rgomezjnr** [comment]
Thanks for checking. I submitted the release package to the Cura Marketplace. When it's approved I'll close the issue.

**Comment by rgomezjnr** [comment]
Hello Di3mex,

Version 1.3.1 has been released on the Cura Marketplace. You can now download the released version from the marketplace.

https://marketplace.ultimaker.com/app/cura/plugins/rgomezjnr/GcodeFilenameFormat

I'll close the issue. Let me know if you have any other quesions or feedback. Thanks again.
