### ISSUE TITLE
Object count

### ISSUE THREAD

**Issue by devonjones** [rgomezjnr/GcodeFilenameFormat#4]
Would it be possible to add an option for the number of objects to be printed?  I regularly modify my file names to add in the count when I have many objects being printed.

**Comment by rgomezjnr** [comment]
Hi yeah sure I can see about adding that

**Comment by rgomezjnr** [comment]
Hey devon I added the object_count option in [1.4.1-rc2](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/1.4.1-rc2). Can you test this please? You will need to download it and copy it to your Cura plugins folder. If it's working for you I can release it to the Cura Marketplace. Thanks.

`[base_name] x[object_count] [profile_name] [brand] [material] lw [line_width]mm lh [layer_height]mm if [infill_sparse_density]% ext1 [material_print_temperature]C bed [material_bed_temperature]C`

`PI3MK3M_paperclip x4 Draft Generic PLA lw 0.8mm lh 0.2mm if 20% ext1 200C bed 60C.gcode`

**Comment by rgomezjnr** [comment]
Hello Devon the object_count option has been added in the release version 1.4.1 which you can download from the Cura Marketplace.
