### ISSUE TITLE
Include Cura version

### ISSUE THREAD

**Issue by mahtDFR** [rgomezjnr/GcodeFilenameFormat#5]
Was just playing with this and think it would be useful to include the version of Cura the gcode is sliced in. Sometimes people test different models in different versions (I'm doing that now actually).

What do you think?

**Comment by rgomezjnr** [comment]
Sure I'll see about adding the Cura version in the format.

**Comment by rgomezjnr** [comment]
Hey maht,

I added the cura_version option in [1.4.1-rc3](https://github.com/rgomezjnr/GcodeFilenameFormat/releases/tag/1.4.1-rc3).

`[base_name] [profile_name] [brand] [material] v[cura_version]
`

![image](https://user-images.githubusercontent.com/55524335/82622120-d1c2f700-9b91-11ea-8e0e-c37873a59d35.png)

I'll add this to the next release 1.4.1.

**Comment by mahtDFR** [comment]
Awesome!

**Comment by mahtDFR** [comment]
Just tested this in 4.4.1, 4.5, and 4.6.1. Works great with the new `[cura_version]` argument, nice work. The devs will do a code review and we'll get it into the Marketplace before the end of the week.
